sudo: false

jdk:
  - oraclejdk8

language: java

before_install:
  - wget https://github.com/google/protobuf/releases/download/v3.2.0/protoc-3.2.0-linux-x86_64.zip
  - unzip protoc-3.2.0-linux-x86_64.zip
  - export PATH=$PATH:$PWD/bin/

install: mvn install -U -DskipTests=true

before_script:
  - export PATH=$PATH:$PWD/bin/

script: mvn install -Dmaven.javadoc.skip=true

env:
  global:
    - secure: BLrgOI/+7cvhvKTNkxWnHrp8XKKb4FHZ2ftKLa6pLeItLE4krQlUPph5xYS3ve6ZMtOKq9koVXjtlCssQLN701r0x5KdPxRZVT2wOqU8uSOxWZsqQ89jbCqKoNukz1jkUzEVsX4ajFm7oUdBmj9d/S6lIHAC85R77D9YQ7s8zd+1p8oleiaSg/4TcOc36oGor38p23UFtGATi5J2mzLQzeKaTZDamuWinpfN71R2332tUXAG1VLCAhEQa8SCmfANdav9CLGhR4Acz+u51h/4oDFVNxjdt5fi3u3Ig+Q3f5xjnyqQqC8+8I/Gocv3y4MFhRWvh/u5b4LjNQ20eb7DzqKPwhGJEVN6NekLYOC3a9HfjsUfZluS4Q4Ip/X864QgqN3ZTxRaZUSTT+h52wEH2jPUNZvJzasLnTCdLTvlmhYJbGbItuFPSfRg6WJCG9lQ7d4wvf7DPTytg2CsWfUzvclICup4v4ymf6j/JzyMYrbAWGy4sPRrEqocv6zYw+r4T6ximS7mguKPApSwFTSBwcM0nWH5YUeq+QeD0kHmvEv5HTiIiqkSQdl8Q3pTgf7BPSaCazC7Rym91eNm5om+NT2G8CfSSYo5OSKi+CpqudRCnCYyrBhqHZy/zDFZIEkL5zcRCS+JVcVNWF50Fly56Tv6aCR+7SSSWBOilh8bBVk=
    - secure: KQwlBnT6i8h4xu5Mcja7HbHIy+Sz2sYfKvHxiCrOeEGOg1lhfsa/kd/LNkayAUxiUa9nLIes9unRG0pa2y8gauO7WWKUtVaYN1pFytHKUqvQe3qkebAIxkA2Mf+Vn6ROeWd51668K17J03h3KgU9jj9//80NvgW2v6yGfRE31JKzplhkb7H1NgDJStmiEbi5ixV1Nl+x8UgZ5dmw/6fAZExLUhh7cnvKHRpRuW2/NR5XTIhsAp2546UsrUygtbhr9yCCamr6tCvpzYGB9gGqV3lfe0XioVSnbJZnk70Yq2X7kv19spZAxB+Pw40GVcakdi6g0hcaP6lAZF2IQhORz9YuRXvy3yhoQut4VGJ8SH946AJPJwGohDxI94XaNt9tdWqUIwUbS8hSk43pyWTy4TlpQCustiSu1vu5PmWUHk2L2DNC6B9oCGRauLxnNF/TASCWZujcZhJ/zxTt+oVaTdIaOALOkG7UazynLzrl7pmrOGrTnB8hsmQbGw7XcSMNlVwkGrN/Cb0meoZ6eaxjsCBgQ4w7dT/GmINyB816NScxp0XxeZe4IbcLhwniaQSz1EOyy/PMn/gg0IqYymu8fFyM/hkfr5n31J3supOg/P+Uf2BNec6kmui2aNRhkkrQ4CizlP/BEDqfY0nskHogJMM5fsP/gL1zb+uGjd8lYbU=
    - secure: GscLEZK/ln7uMzEQep0Ox6C4GwC9X/agLeSc48iZoYISj2pUPQsQK8uqoZtfDl7g0xGx22yJR4ds7tSrAHl0DqhxNqVj+Nxs4/AtD/oTsl1HtQbpJsN4RwyD7G21/lmUAWWt3g+cVaOYtQdSbHMpZpQVZRNxGdLs8qnpYoGJKHlFR5+8dsftqWDOApEyE3BXUqDkNgC3Z6ipRy23EpuGzWEwZb6JWVsQ6brrWZQGgonhzZXJjsdXKx4hcHMiMZqXWE6y9PIPOFppHYNUzxj039aRpjaa6sufx8d3Y6yTxshivudxJZS4A0EBBDY3zYE98NLx5qa/mfVloRir7SWTvwV0UQfemwbEtFV1S8bfMgUxY3+terI7mO4XNugaq5nGprJAENrMNpUWhHWwoapeGrlS3CXr3L0t/Kt8Mwtrblajyphpx6O9kquQXiotIPIfTskAtS2OZ3R2J3g5g2ztsdjPr5GoTXA7HOrmlGTlYlacv0DPFFeYm/9OQ39ndm+qAqiIrAosc6oGedNp/F3yaP9iEx6W1AP168ENr13w4mGBfonnvnkre3MHlrlytCn+OrheSNUJ5pw7SeHiRTXKxKVAicbprEWPgDEgMiFEq9iJ9LG6grVV5T/mTMI4GhQZmiGSoywvmrGfvnvy5DpL5w3sR8kLqIZWcXwiZ4p/UeY=

after_success:
  - ci/deploy_snapshot.sh
  - ci/publish-javadoc-to-gh-pages.sh

branches:
  except:
    - gh-pages
